name: Renovate
on:
  schedule:
    # Runs at 01:00 UTC every Monday
    - cron: '0 1 * * 1'
  # Allows manual triggering of the workflow
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v4.2.2
        - name: Self-hosted Renovate
          uses: renovatebot/github-action@v41.0.5
          with:
            configurationFile: renovate.json
            token: ${{ secrets.RENOVATE_TOKEN }}
          env:
            RENOVATE_AUTODISCOVER: 'true'
